# Porta do servidor
server.port=8080

# Configurações do MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/meusHabitos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Estacio123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# O JPA vai criar as tabelas automaticamente baseado nas nossas classes!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está fazendo por baixo dos panos (ótimo para aprender)
spring.jpa.show-sql=true