# Porta do servidor
server.port=${PORT:8080}

# Configurações do MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# O JPA vai criar as tabelas automaticamente baseado nas nossas classes!
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring está fazendo por baixo dos panos (ótimo para aprender)
spring.jpa.show-sql=false