# Porta do servidor
server.port=${PORT:8080}

# Configuracoes do MySQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# O JPA vai criar as tabelas automaticamente baseado nas nossas classes
spring.jpa.hibernate.ddl-auto=update

# Mostra no console os comandos SQL que o Spring esta fazendo por baixo dos panos
spring.jpa.show-sql=false
